name: auto-merge
on:    
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
    branches:
    - master    
    - main     
  check_suite:
    types:
      - completed
    branches:
    - main        
    - master
  status: 
    branches:
    - main   
    - master     

jobs:
  auto-merge-to-master:
    runs-on: self-hosted
    steps:
    - name: automerge
      uses: "pascalgn/automerge-action@v0.12.0"
