name: role-plex
# This action is called on a push to any branch except master. Why? 
# It enables a development model where a branch can be iterated upon while testing
# just _one_ role, without having to re-validate the entire playbook, which is what happens
# as soon as a PR is created

on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/roles/plex/**'
      - 'plex/**'
    exclude_branches:
      - 'master' # no point in re-testing all this on merge-to-master, we'll rather do a more comprehensive test
      - 'main'   # eventually we'll transistion "master" to "main"
jobs:
  test-plex:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy 
      run: | 
        cd ansible
        ANSIBLE_CONFIG=ansible-ci.cfg ansible-playbook -i hosts.ci deploy.yml -t plex -e ci_validation=true
